# Generated by Django 3.2.7 on 2021-09-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_currency_code', models.CharField(max_length=3)),
                ('from_currency_name', models.TextField()),
                ('to_currency_code', models.CharField(max_length=3)),
                ('to_currency_name', models.TextField()),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=16)),
                ('bid_price', models.DecimalField(decimal_places=8, max_digits=16)),
                ('ask_price', models.DecimalField(decimal_places=8, max_digits=16)),
                ('last_refreshed', models.DateTimeField()),
            ],
        ),
    ]
